[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustlib"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "playground"

[[bin]]
name = "generate_pyi"

[dependencies]
pyo3 = { version = "0.23.5", features = ["abi3", "experimental-inspect", "abi3-py37", "extension-module"] }
numpy = { version = "0.23.0", features = ["half"] }
lz4-sys = { git = "https://github.com/REDxEYE/lz4-rs" }
zstd = "0.13.2"
binread = "2.2.0"
bitflags = "2.6.0"
regex = "1.10.5"
thiserror = "2.0.12"
byteorder = "1.5.0"
uuid = { version = "1.10.0", features = ["v4"] }
half = { version = "2.4.1", features = ["std", "zerocopy"] }
nalgebra = { version = "0.33.0" }
fnmatch-regex2 = "0.3.0"
rayon = "1.10.0"

vtflib2 = { git = "https://github.com/lasa01/vtflib2-rs", features = ["static"] }
texture2ddecoder = { version = "0.1.1", features = ["alloc"] }
png = "0.17.13"
exr = "1.73.0"
image = { version = "0.25.5", features = ["rayon", "exr"], default-features = false }
fast_image_resize = "5.1.2" 
bcndecode = "0.2.0" 
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"

#[patch."https://github.com/lasa01/vtflib2-sys"]
#vtflib2-sys = { git = "https://github.com/REDxEYE/vtflib2-sys"}

[dev-dependencies]
binary-reader = "0.4.5"

[profile.release]
debug = true
lto = true
