[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustlib"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "playground"
path = "src/main.rs"

[dependencies]
pyo3 = { version = "0.21.1", features = ["abi3", "experimental-inspect"] }
numpy = { version = "0.21.0", features = ["half"] }
lzham-alpha-sys = "0.1.1"
lz4 = "1.24.0"
zstd = "0.13.1"
binread = "2.2.0"
bitflags = "2.5.0"
regex = "1.10.4"
thiserror = "1.0.58"
byteorder = "1.5.0"
uuid = { version = "1.8.0", features = ["v4"] }
optick = "1.3.4"
log = "0.4.21"
half = { version = "2.4.1", features = ["std", "zerocopy"] }
nalgebra = { version = "0.32.5" }

[dev-dependencies]
binary-reader = "0.4.5"

[profile.release]
debug = true

