use std::io;
use std::io::{Read, Seek, SeekFrom};

use bitflags::bitflags;
use byteorder::{LE, ReadBytesExt};
use nalgebra::Matrix4;

use rustlib::shared::types::{Vector3, Vector4};
use rustlib::utils::reader_utils::FromReader;
use rustlib::utils::reader_utils::ReadExt;
use crate::errors::SourceError::{self, InvalidHeader};

use crate::source_model::model::Bone;
use crate::utils::reader_utils::ReadSeekExt;

bitflags! {
    /// Represents a set of flags.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct StudioHDRFlags: u32 {
        const AUTOGENERATED_HITBOX = 1 << 0;

        // NOTE:  This flag is set at loadtime, not mdl build time so that we don't have to rebuild
        // models when we change materials.
        const USES_ENV_CUBEMAP = 1 << 1;

        // Use this when there are translucent parts to the model but we're not going to sort it
        const FORCE_OPAQUE = 1 << 2;

        // Use this when we want to render the opaque parts during the opaque pass
        // and the translucent parts during the translucent pass
        const TRANSLUCENT_TWOPASS = 1 << 3;

        // This is set any time the .qc files has $staticprop in it
        // Means there's no bones and no transforms
        const STATIC_PROP = 1 << 4;

        // NOTE:  This flag is set at loadtime, not mdl build time so that we don't have to rebuild
        // models when we change materials.
        const USES_FB_TEXTURE = 1 << 5;

        // This flag is set by studiomdl.exe if a separate "$shadowlod" entry was present
        //  for the .mdl (the shadow lod is the last entry in the lod list if present)
        const HASSHADOWLOD = 1 << 6;

        // NOTE:  This flag is set at loadtime, not mdl build time so that we don't have to rebuild
        // models when we change materials.
        const USES_BUMPMAPPING = 1 << 7;

        // NOTE:  This flag is set when we should use the actual materials on the shadow LOD
        // instead of overriding them with the default one (necessary for
        // translucent shadows)
        const USE_SHADOWLOD_MATERIALS = 1 << 8;

        const OBSOLETE = 1 << 9;
        const UNUSED = 1 << 10;

        // NOTE:  This flag is set at mdl build time
        const NO_FORCED_FADE = 1 << 11;

        // NOTE:  The npc will lengthen the viseme check to always include two
        // phonemes
        const FORCE_PHONEME_CROSSFADE = 1 << 12;

        // This flag is set when the .qc has $constantdirectionallight in it
        // If set, we use constantdirectionallightdot to calculate light intensity
        // rather than the normal directional dot product
        // only valid if STATIC_PROP is also set
        const CONSTANT_DIRECTIONAL_LIGHT_DOT = 1 << 13;

        // Flag to mark delta flexes as already converted from disk format to
        // memory format
        const FLEXES_CONVERTED = 1 << 14;

        // Indicates the studiomdl was built in preview mode
        const BUILT_IN_PREVIEW_MODE = 1 << 15;

        // Ambient boost (runtime flag)
        const AMBIENT_BOOST = 1 << 16;

        // Don't cast shadows from this model (useful on first-person models)
        const DO_NOT_CAST_SHADOWS = 1 << 17;

        // alpha textures should cast shadows in vrad on this model (ONLY prop_static!)
        const CAST_TEXTURE_SHADOWS = 1 << 18;

        const SUBDIVISION_SURFACE = 1 << 19;

        // flagged on load to indicate no animation events on this model
        const VERT_ANIM_FIXED_POINT_SCALE = 1 << 21;
    }
}
bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct StudioBoneFlags:u32{
        // BONE_CALCULATE_MASK = 0x1F
        const PHYSICALLY_SIMULATED = 0x01;  // bone is physically simulated when physics are active
        const PHYSICS_PROCEDURAL = 0x02;  // procedural when physics is active
        const ALWAYS_PROCEDURAL = 0x04;  // bone is always procedurally animated
        // bone aligns to the screen, not constrained in motion.
        const SCREEN_ALIGN_SPHERE = 0x08;
        // bone aligns to the screen, constrained by it's own axis.
        const SCREEN_ALIGN_CYLINDER = 0x10;

        // BONE_USED_MASK = 0x0007FF00
        const USED_BY_ANYTHING = 0x0007FF00;
        const USED_BY_HITBOX = 0x00000100;  // bone (or child) is used by a hit box
        // bone (or child) is used by an attachment point
        const USED_BY_ATTACHMENT = 0x00000200;
        const USED_BY_VERTEX_MASK = 0x0003FC00;
        // bone (or child) is used by the toplevel model via skinned vertex
        const USED_BY_VERTEX_LOD0 = 0x00000400;
        const USED_BY_VERTEX_LOD1 = 0x00000800;
        const USED_BY_VERTEX_LOD2 = 0x00001000;
        const USED_BY_VERTEX_LOD3 = 0x00002000;
        const USED_BY_VERTEX_LOD4 = 0x00004000;
        const USED_BY_VERTEX_LOD5 = 0x00008000;
        const USED_BY_VERTEX_LOD6 = 0x00010000;
        const USED_BY_VERTEX_LOD7 = 0x00020000;
        // bone is available for bone merge to occur against it
        const USED_BY_BONE_MERGE = 0x00040000;
    }
}



impl<R: Seek + Read> FromReader<R> for StudioHDRFlags {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        Ok(StudioHDRFlags::from_bits_retain(reader.read_u32le()?))
    }
}

impl<R: Seek + Read> FromReader<R> for StudioBoneFlags {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        Ok(StudioBoneFlags::from_bits_retain(reader.read_u32le()?))
    }
}


#[derive(Debug)]
pub struct StudioBoneV49 {
    name: String,
    parent_id: i32,
    bone_controller_ids: [f32; 6],
    position: Vector3,
    quat: Vector4,

    rotation: Vector3,
    position_scale: Vector3,
    rotation_scale: Vector3,

    pose_to_bone: [f32; 12],
    q_alignment: Vector4,
    flags: StudioBoneFlags,
    procedural_rule_type: u32,
    procedural_rule_offset: u32,
    physics_bone_index: u32,

    surface_prop: String,

    contents: u32,
    _pad: [u32; 8],

}

impl<R: Read + Seek> FromReader<R> for StudioBoneV49 {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        let entry = reader.stream_position()?;
        Ok(StudioBoneV49 {
            name: reader.read_pztstring(entry)?,
            parent_id: reader.read_i32le()?,
            bone_controller_ids: [reader.read_f32le()?, reader.read_f32le()?, reader.read_f32le()?, reader.read_f32le()?, reader.read_f32le()?, reader.read_f32le()?],
            position: Vector3::from_reader(reader)?,
            quat: Vector4::from_reader(reader)?,
            rotation: Vector3::from_reader(reader)?,
            position_scale: Vector3::from_reader(reader)?,
            rotation_scale: Vector3::from_reader(reader)?,
            pose_to_bone: {
                let mut items = [0f32; 12];
                reader.read_f32_into::<LE>(&mut items)?;
                items
            },
            q_alignment: Vector4::from_reader(reader)?,
            flags: StudioBoneFlags::from_bits_retain(reader.read_u32le()?),
            procedural_rule_type: reader.read_u32le()?,
            procedural_rule_offset: reader.read_u32le()?,
            physics_bone_index: reader.read_u32le()?,
            surface_prop: reader.read_pztstring(entry)?,
            contents: reader.read_u32le()?,
            _pad: {
                let mut items = [0u32; 8];
                reader.read_u32_into::<LE>(&mut items)?;
                items
            },
        })
    }
}

impl From<StudioBoneV49> for Bone {
    fn from(value: StudioBoneV49) -> Self {
        Bone {
            name: value.name,
            parent: value.parent_id,
            matrix: (Matrix4::new_translation(&value.position.into())
                * Matrix4::from_euler_angles(value.rotation.x, value.rotation.y, value.rotation.z)),
        }
    }
}

#[derive(Debug)]
pub struct StudioMaterialV49 {
    name: String,
    flags: u32,
    used: u32,
    unused1: u32,
    material_pointer: u32,
    client_material_pointer: u32,
    _pad: [u32; 10],
}

impl<R: Read + Seek> FromReader<R> for StudioMaterialV49 {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        let base = reader.stream_position()?;

        Ok(StudioMaterialV49 {
            name: reader.read_pztstring(base)?,
            flags: reader.read_u32le()?,
            used: reader.read_u32le()?,
            unused1: reader.read_u32le()?,
            material_pointer: reader.read_u32le()?,
            client_material_pointer: reader.read_u32le()?,
            _pad: {
                let mut items = [0u32; 10];
                reader.read_u32_into::<LE>(&mut items)?;
                items
            },
        })
    }
}

pub struct StudioSkinGroup(Vec<u16>);

#[derive(Debug)]
#[repr(C)]
pub struct StudioMdlHeaderV49 {
    pub ident: u32,
    pub version: u32,
    pub checksum: u32,
    pub name: String,
    pub file_size: u32,
    pub eye_position: Vector3,
    pub illumination_position: Vector3,
    pub hull_min: Vector3,
    pub hull_max: Vector3,
    pub view_bbox_min: Vector3,
    pub view_bbox_max: Vector3,

    pub flags: StudioHDRFlags,

    pub bone_count: u32,
    pub bone_offset: u64,

    pub bone_controller_count: u32,
    pub bone_controller_offset: u64,
    pub hitbox_set_count: u32,
    pub hitbox_set_offset: u64,
    pub local_animation_count: u32,
    pub local_animation_offset: u64,
    pub local_sequence_count: u32,
    pub local_sequence_offset: u64,
    pub activity_list_version: u32,
    pub events_indexed: u32,

    pub texture_count: u32,
    pub textures_offset: u64,

    pub texture_path_count: u32,
    pub texture_paths_offset: u64,

    pub skin_reference_count: u32,
    pub skin_family_count: u32,
    pub skin_groups_offset: u64,

    pub body_part_count: u32,
    pub body_part_offset: u64,

    pub local_attachment_count: u32,
    pub local_attachment_offset: u64,

    pub local_node_count: u32,
    pub local_node_offset: u64,
    pub local_node_name_offset: u64,

    pub flex_desc_count: u32,
    pub flex_desc_offset: u64,
    pub flex_controller_count: u32,
    pub flex_controller_offset: u64,
    pub flex_rule_count: u32,
    pub flex_rule_offset: u64,
    pub ik_chain_count: u32,
    pub ik_chain_offset: u64,
    pub mouth_count: u32,
    pub mouth_offset: u64,
    pub local_pose_paramater_count: u32,
    pub local_pose_parameter_offset: u64,

    pub surface_prop: String,

    pub key_value_offset: u64,
    pub key_value_size: u32,
    pub local_ik_auto_play_lock_count: u32,
    pub local_ik_auto_play_lock_offset: u64,
    pub mass: f32,
    pub contents: u32,

    pub include_model_count: u32,
    pub include_model_offset: u64,
    pub virtual_model_pointer: u32,
    pub anim_block_name: String,
    pub anim_block_count: u32,
    pub anim_block_offset: u64,
    pub anim_block_model_pointer: u32,
    pub bone_table_by_name_offset: u32,
    pub vertex_base_pointer: u32,
    pub index_base_pointer: u32,
    pub directional_light_dot: u8,
    pub root_lod: u8,
    pub allowed_root_lod_count: u8,
    pub unused4: u8,
    pub flex_controller_ui_count: u32,
    pub flex_controller_ui_offset: u64,
    pub vert_anim_fixed_point_scale: f32,
    pub unused3: u32,
    pub studio_header2_offset: u32,
    pub unused2: u32,
    pub source_bone_transform_count: u32,
    pub source_bone_transform_offset: u64,
    pub illum_position_attachment_index: u32,
    pub max_eye_deflection: f32,
    pub linear_bone_offset: u64,
    pub bone_flex_driver_count: u32,
    pub bone_flex_driver_offset: u64,
}

impl<R: Read + Seek> FromReader<R> for StudioMdlHeaderV49 {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        Ok(StudioMdlHeaderV49 {
            ident: reader.read_u32le()?,
            version: reader.read_u32le()?,
            checksum: reader.read_u32le()?,
            name: reader.read_fixed_string(64)?,
            file_size: reader.read_u32le()?,
            eye_position: Vector3::from_reader(reader)?,
            illumination_position: Vector3::from_reader(reader)?,
            hull_min: Vector3::from_reader(reader)?,
            hull_max: Vector3::from_reader(reader)?,
            view_bbox_min: Vector3::from_reader(reader)?,
            view_bbox_max: Vector3::from_reader(reader)?,
            flags: StudioHDRFlags::from_bits_retain(reader.read_u32le()?),
            bone_count: reader.read_u32le()?,
            bone_offset: reader.read_u32le()? as u64,
            bone_controller_count: reader.read_u32le()?,
            bone_controller_offset: reader.read_u32le()? as u64,
            hitbox_set_count: reader.read_u32le()?,
            hitbox_set_offset: reader.read_u32le()? as u64,
            local_animation_count: reader.read_u32le()?,
            local_animation_offset: reader.read_u32le()? as u64,
            local_sequence_count: reader.read_u32le()?,
            local_sequence_offset: reader.read_u32le()? as u64,
            activity_list_version: reader.read_u32le()?,
            events_indexed: reader.read_u32le()?,
            texture_count: reader.read_u32le()?,
            textures_offset: reader.read_u32le()? as u64,
            texture_path_count: reader.read_u32le()?,
            texture_paths_offset: reader.read_u32le()? as u64,
            skin_reference_count: reader.read_u32le()?,
            skin_family_count: reader.read_u32le()?,
            skin_groups_offset: reader.read_u32le()? as u64,
            body_part_count: reader.read_u32le()?,
            body_part_offset: reader.read_u32le()? as u64,
            local_attachment_count: reader.read_u32le()?,
            local_attachment_offset: reader.read_u32le()? as u64,
            local_node_count: reader.read_u32le()?,
            local_node_offset: reader.read_u32le()? as u64,
            local_node_name_offset: reader.read_u32le()? as u64,
            flex_desc_count: reader.read_u32le()?,
            flex_desc_offset: reader.read_u32le()? as u64,
            flex_controller_count: reader.read_u32le()?,
            flex_controller_offset: reader.read_u32le()? as u64,
            flex_rule_count: reader.read_u32le()?,
            flex_rule_offset: reader.read_u32le()? as u64,
            ik_chain_count: reader.read_u32le()?,
            ik_chain_offset: reader.read_u32le()? as u64,
            mouth_count: reader.read_u32le()?,
            mouth_offset: reader.read_u32le()? as u64,
            local_pose_paramater_count: reader.read_u32le()?,
            local_pose_parameter_offset: reader.read_u32le()? as u64,
            surface_prop: reader.read_pztstring(0)?,
            key_value_offset: reader.read_u32le()? as u64,
            key_value_size: reader.read_u32le()?,
            local_ik_auto_play_lock_count: reader.read_u32le()?,
            local_ik_auto_play_lock_offset: reader.read_u32le()? as u64,
            mass: reader.read_f32le()?,
            contents: reader.read_u32le()?,
            include_model_count: reader.read_u32le()?,
            include_model_offset: reader.read_u32le()? as u64,
            virtual_model_pointer: reader.read_u32le()?,
            anim_block_name: reader.read_pztstring(0)?,
            anim_block_count: reader.read_u32le()?,
            anim_block_offset: reader.read_u32le()? as u64,
            anim_block_model_pointer: reader.read_u32le()?,
            bone_table_by_name_offset: reader.read_u32le()?,
            vertex_base_pointer: reader.read_u32le()?,
            index_base_pointer: reader.read_u32le()?,
            directional_light_dot: reader.read_u8()?,
            root_lod: reader.read_u8()?,
            allowed_root_lod_count: reader.read_u8()?,
            unused4: reader.read_u8()?,
            flex_controller_ui_count: reader.read_u32le()?,
            flex_controller_ui_offset: reader.read_u32le()? as u64,
            vert_anim_fixed_point_scale: reader.read_f32le()?,
            unused3: reader.read_u32le()?,
            studio_header2_offset: reader.read_u32le()?,
            unused2: reader.read_u32le()?,
            source_bone_transform_count: reader.read_u32le()?,
            source_bone_transform_offset: reader.read_u32le()? as u64,
            illum_position_attachment_index: reader.read_u32le()?,
            max_eye_deflection: reader.read_f32le()?,
            linear_bone_offset: reader.read_u32le()? as u64,
            bone_flex_driver_count: reader.read_u32le()?,
            bone_flex_driver_offset: reader.read_u32le()? as u64,
        })
    }
}


#[derive(Debug)]
pub struct StudioVertexAnimV49 {
    pub index: u16,
    pub speed: u8,
    pub side: u8,
    pub vertex_delta: [f32; 3],
    pub normal_delta: [f32; 3],
}

impl<R: Read + Seek> FromReader<R> for StudioVertexAnimV49 {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        Ok(StudioVertexAnimV49 {
            index: reader.read_u16le()?,
            speed: reader.read_u8()?,
            side: reader.read_u8()?,
            vertex_delta: [reader.read_f16le()?, reader.read_f16le()?, reader.read_f16le()?],
            normal_delta: [reader.read_f16le()?, reader.read_f16le()?, reader.read_f16le()?],
        })
    }
}

bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct StudioVertexAninationType:u8{
        const NORMAL = 0;
        const WRINKLE = 1;
    }
}
#[derive(Debug)]
pub struct Flex {
    pub flex_desc_id: u32,
    pub targets: [f32; 4],
    pub vertex_count: u32,
    pub vertex_offset: u64,
    pub partner_id: i32,
    pub anim_type: StudioVertexAninationType,
    pub unused: [u8; 3],
    pub unused2: [u32; 6],
}

impl Flex {
    pub fn get_vertex_anims<R: Read + Seek>(&self, reader: &mut R) -> io::Result<Vec<StudioVertexAnimV49>> {
        reader.seek(SeekFrom::Start(self.vertex_offset))?;
        let mut anims = Vec::with_capacity(self.vertex_count as usize);
        for _ in 0..self.vertex_count {
            anims.push(StudioVertexAnimV49::from_reader(reader)?);
        }
        Ok(anims)
    }
}

impl<R: Read + Seek> FromReader<R> for Flex {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        let base = reader.stream_position()?;
        Ok(Flex {
            flex_desc_id: reader.read_u32le()?,
            targets: [reader.read_f32le()?, reader.read_f32le()?, reader.read_f32le()?, reader.read_f32le()?],
            vertex_count: reader.read_u32le()?,
            vertex_offset: reader.read_relptr(base)?,
            partner_id: reader.read_i32le()?,
            anim_type: StudioVertexAninationType::from_bits_retain(reader.read_u8()?),
            unused: [reader.read_u8()?, reader.read_u8()?, reader.read_u8()?],
            unused2: {
                let mut tmp = [0u32; 6];
                reader.read_u32_into::<LE>(&mut tmp)?;
                tmp
            },
        })
    }
}

#[derive(Debug)]
pub struct StudioMeshV49 {
    pub material_id: u32,
    pub model_offset: u64,
    pub vertex_count: u32,
    pub vertex_start: u32,
    pub flex_count: u32,
    pub flex_offset: u64,
    pub material_type: u32,
    pub material_param: u32,
    pub mesh_id: u32,
    pub center: Vector3,
    pub unused: [u32; 17],
}

impl StudioMeshV49 {
    pub fn get_flexes<R: Read + Seek>(&self, reader: &mut R) -> io::Result<Vec<Flex>> {
        reader.seek(SeekFrom::Start(self.flex_offset))?;
        let mut flexes = Vec::with_capacity(self.flex_count as usize);
        for _ in 0..self.flex_count {
            flexes.push(Flex::from_reader(reader)?)
        }
        Ok(flexes)
    }
}

impl<R: Read + Seek> FromReader<R> for StudioMeshV49 {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        let base = reader.stream_position()?;
        Ok(StudioMeshV49 {
            material_id: reader.read_u32le()?,
            model_offset: reader.read_relptr(base)?,
            vertex_count: reader.read_u32le()?,
            vertex_start: reader.read_u32le()?,
            flex_count: reader.read_u32le()?,
            flex_offset: reader.read_relptr(base)?,
            material_type: reader.read_u32le()?,
            material_param: reader.read_u32le()?,
            mesh_id: reader.read_u32le()?,
            center: Vector3::from_reader(reader)?,
            unused: {
                let mut tmp = [0u32; 17];
                reader.read_u32_into::<LE>(&mut tmp)?;
                tmp
            },
        })
    }
}

#[derive(Debug)]
pub struct StudioModel {
    pub name: String,
    pub mod_type: u32,
    pub bounding_radius: f32,
    pub mesh_count: u32,
    pub mesh_offset: u64,
    pub vertex_count: u32,
    pub vertex_offset: u64,
    pub tangent_offset: u64,
    pub attachment_count: u32,
    pub attachment_offset: u64,
    pub eyeball_count: u32,
    pub eyeball_offset: u64,
    pub vertex_data: [u32; 2],
    pub unused: [u32; 8],
}


impl<R: Read + Seek> FromReader<R> for StudioModel {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        let base = reader.stream_position()?;
        Ok(StudioModel {
            name: reader.read_fixed_string(64)?,
            mod_type: reader.read_u32le()?,
            bounding_radius: reader.read_f32le()?,
            mesh_count: reader.read_u32le()?,
            mesh_offset: reader.read_relptr(base)?,
            vertex_count: reader.read_u32le()?,
            vertex_offset: reader.read_relptr(base)?,
            tangent_offset: reader.read_relptr(base)?,
            attachment_count: reader.read_u32le()?,
            attachment_offset: reader.read_relptr(base)?,
            eyeball_count: reader.read_u32le()?,
            eyeball_offset: reader.read_relptr(base)?,
            vertex_data: [reader.read_u32le()?, reader.read_u32le()?],
            unused: [reader.read_u32le()?, reader.read_u32le()?, reader.read_u32le()?, reader.read_u32le()?, reader.read_u32le()?, reader.read_u32le()?, reader.read_u32le()?, reader.read_u32le()?],
        })
    }
}

impl StudioModel {
    pub fn get_meshes<R: Read + Seek>(&self, reader: &mut R) -> io::Result<Vec<StudioMeshV49>> {
        reader.seek(SeekFrom::Start(self.mesh_offset))?;
        let mut meshes = Vec::with_capacity(self.mesh_count as usize);
        for _ in 0..self.mesh_count {
            let mesh = StudioMeshV49::from_reader(reader)?;
            println!("{:#?}", mesh);
            meshes.push(mesh);
        }
        Ok(meshes)
    }
}

#[derive(Debug)]
pub struct StudioBodypart {
    pub name: String,
    pub model_count: u32,
    pub base: u64,
    pub model_offset: u64,
}

impl<R: Read + Seek> FromReader<R> for StudioBodypart {
    fn from_reader(reader: &mut R) -> io::Result<Self> {
        let base = reader.stream_position()?;
        Ok(StudioBodypart {
            name: reader.read_pztstring(base)?,
            model_count: reader.read_u32le()?,
            base: reader.read_relptr(base)?,
            model_offset: reader.read_relptr(base)?,
        })
    }
}

impl StudioBodypart {
    pub fn get_models<R: Read + Seek>(&self, reader: &mut R) -> io::Result<Vec<StudioModel>> {
        reader.seek(SeekFrom::Start(self.model_offset))?;
        let mut model = Vec::with_capacity(self.model_count as usize);
        for _ in 0..self.model_count {
            model.push(StudioModel::from_reader(reader)?)
        }
        Ok(model)
    }
}

#[derive(Debug)]
pub struct Mdl {
    header: StudioMdlHeaderV49,
    bones: Vec<StudioBoneV49>,
    materials: Vec<StudioMaterialV49>,
    pub material_paths: Vec<String>,
    pub flex_names: Vec<String>,
    pub bodyparts: Vec<StudioBodypart>,
}

pub fn read_mdl_v49<R: Read + Seek>(reader: &mut R) -> Result<Mdl, SourceError> {
    let header = StudioMdlHeaderV49::from_reader(reader)?;

    if header.ident != u32::from_le_bytes(*b"IDST") {
        return Err(InvalidHeader("MDL".into(), header.ident.to_le_bytes(), *b"IDST"));
    }

    reader.seek(SeekFrom::Start(header.bone_offset))?;
    let mut bones = Vec::with_capacity(header.bone_count as usize);
    for _ in 0..header.bone_count {
        bones.push(StudioBoneV49::from_reader(reader)?);
    }
    reader.seek(SeekFrom::Start(header.textures_offset))?;
    let mut materials = Vec::with_capacity(header.texture_count as usize);
    for _ in 0..header.texture_count {
        materials.push(StudioMaterialV49::from_reader(reader)?);
    }
    reader.seek(SeekFrom::Start(header.texture_paths_offset))?;
    let mut material_paths = Vec::with_capacity(header.texture_path_count as usize);
    for _ in 0..header.texture_path_count {
        let string = reader.read_pztstring(0)?;
        material_paths.push(string);
    }
    reader.seek(SeekFrom::Start(header.skin_groups_offset))?;
    let mut skin_groups = Vec::with_capacity(header.skin_family_count as usize);
    for _ in 0..header.skin_family_count {
        let mut skin_group = vec![0u16; header.skin_reference_count as usize];
        reader.read_u16_into::<LE>(&mut skin_group)?;
        skin_groups.push(skin_group);
    }

    reader.seek(SeekFrom::Start(header.flex_desc_offset))?;
    let mut flex_names = Vec::with_capacity(header.flex_desc_count as usize);
    for _ in 0..header.flex_desc_count {
        let base = reader.stream_position()?;
        flex_names.push(reader.read_pztstring(base)?);
    }

    reader.seek(SeekFrom::Start(header.body_part_offset))?;
    let mut bodyparts = Vec::with_capacity(header.body_part_count as usize);
    for _ in 0..header.body_part_count {
        bodyparts.push(StudioBodypart::from_reader(reader)?);
    }

    Ok(Mdl { header, bones, materials, material_paths, flex_names, bodyparts })
}